# Generated by Django 4.1.7 on 2023-03-31 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='', verbose_name='media/product')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
